Mlem/Models/User-Interactable/Comment.swift
This is a quick recursive method to insert a reply into a Comment. You may want to adapt this to your own code style.
=> Add Comment.insertReply method

Mlem/Models/User-Interactable/Comment.swift
I added both Comment.replaceReply() and Comment.removeReply().
removeReply might be handy if someone decides to delete their comment.
Closes https://github.com/buresdv/Mlem/issues/12
=> Add Comment.replaceReply and .removeReply

Mlem/API/Requests/GetPostsRequest.swift, Mlem/Extensions/JSONDecoder+Default.swift, Mlem/Logic/Networking/Infinite Loader.swift, Mlem/Logic/Time Parser.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
This PR addresses some of the issues described in #115 
- Ensures the `feedType` is correctly send through to our post loader
- Fixes the missing `Cancel` button in community search which must've been lost in a rebase 🙈 
- Adjusts date formatter to use `.gmt` for correct relative dating, also adds a small catch to avoid showing `in 0` when a …
=> Fix - API change regressions

Mlem/API/Models/APISite.swift
=> Fix Date instead of String

Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Large Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Post Header.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Post Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Vote Complex/Vote Complex.swift
Relates to https://github.com/buresdv/Mlem/issues/108
Fixes grouping for certain accessibility elements.
Adds makes voting use "adjustable" interaction type, so you can vote by swiping up or down.
Fixes issues with Comments voting.
https://streamable.com/uxandh
More to come, trying to limit my reach till UI stabilizes.
=> Improved VO for Post and Comments.

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
Relates to https://github.com/buresdv/Mlem/issues/106
Fixes issue where community search view was not scaling properly.
Fixes issue where VO would read elements from the search view while it was hidden
https://streamable.com/wafk9a
Still needs some grouping and labeling work but this VASTLY increases functionality.
=> Fix VO issues with community view

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Post Header.swift
- - [x] This PR introduces major changes, and I have consulted @buresdv, @jboi or @mormaer in the *Mlem Development Matrix room*
Added Accessibility Action to view a community from a post with VoiceOver enabled.
https://streamable.com/sj55mo
=> Fix for navigating to community from a post

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Large Post.swift
This PR address a couple of issues that have been discussed today in the development chat ahead of a planned release.
- Multiple error alerts showing while loading feeds
> This appears to be for SSL related errors on Beehaw where I can test, but some screenshots showed the _unhandled_ case firing, which is most likely a decoding related error. Until we …
=> Fix - various 0.0.7 issues

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Post Header.swift
This reverts commit c59ddc14d4c22c47f7b650ef2f69282b478bf72d.
Reversing changes I did to make community navigation accessible. Due to the way NavigationLinks are currently working in the app, this broke navigation on reused views.
Planning to revisit this after we tackle navigation updates.
=> Revert "Fix for navigating to community from a post"

Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift
Just a small PR to address #169 by adapting to use the `VoteComplex` view introduced for posts.
| BEFORE | AFTER |
| --- | --- |
| <img width="370" alt="Screenshot 2023-06-19 at 21 13 01" src="https://github.com/buresdv/Mlem/assets/5231793/ae0423a6-aeac-453a-aecf-45b8fd7c3fcc"> | <img width="368" alt="Screenshot 2023-06-19 at 21 11 03" …
=> fix #169 - update comments to use new voting style

Mlem/ContentView.swift
- - [x] This PR introduces major changes, and I have consulted @buresdv, @jboi or @mormaer in the *Mlem Development Matrix room*
This does not implement the messages tab, but clarifies that it doesn't exist yet.  There was some confusion in the Matrix chat about the tab being broken or causing confusion.
n/a
=> Updated messages tab to show a coming soon message

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Post Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift
Continuation of #98 
New example
https://github.com/buresdv/Mlem/assets/17646836/058842f6-2881-4a18-ae59-edb579e4e9d3
=> Have only one way to share something from a post

Mlem.xcodeproj/project.pbxproj
Cutting the fluff of this PR, I am just updating the dev team for TestFlight.
=> Update Development Team

Mlem/Views/Tabs/Settings/Settings View.swift
Last time I am going to use a bullshit PR description... I promise 😉
=> Merging team changes in from testflight branch.

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar Header.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar.swift, Mlem/Views/Tabs/Posts/Components/Shared/Links/User Profile Label.swift
- - [x] This PR introduces major changes, and I have consulted the *Mlem Development Matrix room*
Updated user labels to take an optional community context to show moderators in the sidebar view.
Also fixed an issue with the sidebar view showing the handle twice instead of the community name.
n/a
=> Updated mods in sidebar to be moderator labels

gpl-3.0.txt
**This file contains the GLP 3.0 license text**
=> gpl 3.0 license file uploaded

Mlem.xcodeproj/project.pbxproj, Mlem/API/Models/Community/APICommunity.swift, Mlem/API/Requests/Community/ListCommunities.swift, Mlem/Logic/Get Favorited Communities.swift, Mlem/Models/Trackers/Favorite Community Tracker.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListRowViews.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListSidebarEntry.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community Search/Community Search View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Accounts Page.swift
Addresses #78
- - [x] This PR introduces major changes, and I have consulted @buresdv, @jboi or @mormaer in the *Mlem Development Matrix room*
The PR add an Apollo-like communities screen.  It is injected between the "Accounts" screen and the "Community View".  This is a natural "home" screen that allows people to select what they want to browse when they first get into the app.
I am brand new to Swift and SwiftUI so please bear with me!
Video demo: …
=> Added new Community List page to the login flow

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Header.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Compact Post.swift
- - [x] This PR introduces major changes, and I have consulted the *Mlem Development Matrix room*
Updates post to use the same format as other places in the app to show user flair.
n/a
=> Updated posts to use full flaired user links

Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift
Just come view cleanup.  No visual changes.
n/a
n/a
=> Community list cleanup

CONTRIBUTING.txt, Mlem.xcodeproj/project.pbxproj, Mlem/App Constants.swift, Mlem/Extensions/Swipey Actions.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Embedded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Compact Post.swift
Added CONTRIBUTING.txt, tweaked swipiness
=> Added CONTRIBUTION.txt, EmbeddedPost

Mlem.xcodeproj/project.pbxproj, Mlem/Extensions/Bundle.swift, Mlem/Views/Tabs/Settings/Settings View.swift
- Bumps us to 0.1.0
- Adds a version field to the settings screen for our own sanity
n/a
n/a
=> Added version to settings screen + version bump

Mlem.xcodeproj/project.pbxproj
We really need CI builds on PRs :)
**In case this PR changes something in the UI, please include screenshots or videos of this new feature**
**Any additional context you'd like to add to help us review this PR**
=> Fixed missing Bundle extension file

Mlem/Views/Tabs/Settings/Components/Views/Appearance.swift
=> Updated shouldShowCommunityHeaders default to true

README.md
**Describe what this PR contains in as much detail as possible**
**In case this PR changes something in the UI, please include screenshots or videos of this new feature**
**Any additional context you'd like to add to help us review this PR**
=> Update README with new screenshots

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community Search/Community Search View.swift
- - [x] This PR introduces major changes, and I have consulted the *Mlem Development Matrix room*
This was a debug option I forgot to remove.
n/a
n/a
=> Removed "Got To Community List" button from community search

commom-clause-1.0.txt
I have also added the Common Clause 1.0 license text file, which includes our org info and app name.
=> common clause license file added

README.md
- - [ ] This PR adds new UI elements/changes the UI, and I have attached pictures or videos of the new / changed UI elements
Updated TestFlight link in README (Fixes #219)
N/A
N/A
=> Update TestFlight link in README

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift
Just some polished inspired from #54.
- Updated default text in reply field to "Commented as {username}" instead of just "{username}"
- Updated replying-to field to use user flair'd labels
n/a
=> Reply field cleanup

Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListRowViews.swift
Just adding more descriptive labels.
I started watching this to get some ideas: https://developer.apple.com/videos/play/wwdc2021/10119/
n/a
n/a
=> Small accessibility updates for Community List View

Mlem/Enums/Sorting Options.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sorting Menu.swift
Added the new sort methods and winged some icons.
n/a
=>  New Feed sort options in API 0.18 need to be added to Mlem #278

Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Add Account View.swift
Bad logic looking at the whole URL and not just the path for version checking.
n/a
n/a
=> Fixed issue with connecting to lemmy instances with domain names containing "v1"

Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Save.swift
Updates the unfavorited icon to be unfilled to make it clearer which state it is in.
Resolves #282
=> Updated "unsaved" favorite icon with an empty icon to make it more clear

Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift
Looks like the post context got stripped in the last round of refactors.
n/a
We should look into some UI-based tests.
=> Fixed OP not being orange in threads

Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item Old.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Header.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Compact Post.swift, Mlem/Views/Tabs/Posts/Components/Shared/Links/User Profile Label.swift, Mlem/Views/Tabs/Posts/Components/Shared/Links/User Profile Link.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance.swift
Saw this on lemmy somewhere and thought it was a nifty.
n/a
=> Added option to show user server instance in posts and comments

.github/pull_request_template.md
**Describe what this PR contains in as much detail as possible**
**In case this PR changes something in the UI, please include screenshots or videos of this new feature**
**Any additional context you'd like to add to help us review this PR**
=> Update pull_request_template.md to reflect new contributing flow

Mlem.xcodeproj/project.pbxproj, Mlem/API/Models/Posts/APIPost.swift, Mlem/API/Models/Users/APIPerson.swift, Mlem/API/Requests/Post/GetPost.swift, Mlem/ContentView.swift, Mlem/Extensions/View - Handle Lemmy Links.swift, Mlem/MlemApp.swift, Mlem/Models/Navigation Contexts/Lazy Load Post Link.swift, Mlem/Models/Trackers/Comment Tracker.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Embedded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar Header Label.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar Header.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Lazy Load Expanded Post.swift, Mlem/Views/Tabs/Posts/Components/Shared/Links/User Profile Label.swift, Mlem/Views/Tabs/Posts/Components/User/Components/User View.swift, Mlem/Views/Tabs/Profile/Profile View.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance.swift
- - [x] This PR introduces major changes, and I have consulted the *Mlem Development Matrix room*
This PR implements the Profile tab!
Features:
- "Overview" tab with a mix of posts/comments
- "Comments" tab for just comments
- "Posts" tab for just posts
- "Saved" tab which only shows up in your own profile and shows your saved comments and posts
You can click on other people's profile and see them as well.
*NOTE:* I did not implement streaming down of pages of content.  That …
=> Implemented Profile Tab

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar Header.swift
- #333
Fixed names getting truncated by allowing them to scale down.
n/a
=> Fixed long name truncation in profile

Mlem.xcodeproj/project.pbxproj, Mlem/Logic/Participating/Delete Post or Comment.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item Logic.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Compact Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Large Post.swift, Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Ellipsis Menu.swift
- #309 
- #310
- [z] If this PR alters the UI, I have attached pictures/videos
This PR pipes down the deletion callback to the ellipse menu used for posts and comments and attempts a deletion call.
I could use some tips on error handling.  Right now it logs and gives a small buzz but does not show the user a visible error.
Addresses #309 and #310
=> Fixed: Favorited communities occasionally show up multiple times #324

.swiftlint.yml
- issue from development chat, urls triggering lint errors
Small change to ignore URLs in our line length checks
=> fix - add exception for URLs in line length checks

.github/workflows/swiftlint.yml, .swiftlint.yml, Mlem.xcodeproj/project.pbxproj, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar Header.swift, Mlem/Views/Tabs/Posts/Components/User/Components/User View.swift, Mlem/Views/Tabs/Settings/Settings View.swift
- *list issue(s) here*
We need this to gate PRs if we want to use it.
This PR adds an action that will error if the pipeline fails and also fixes the remaining warnings.
Notably I disabled the "TODO" warning as we had a ton of those
n/a
n/a
=> Add a swiftlink GitHub action

Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListRowViews.swift
- https://github.com/mormaer/Mlem/issues/352
Fixes some issues related to VO with community view
https://streamable.com/ipde4i
=> Fix community list accessibility

Mlem/Views/Shared/Loading View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Large Post.swift, Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Save.swift, Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Share.swift
Also improved the interaction buttons
Also imrpoved the loading indicator
- https://github.com/mormaer/Mlem/issues/268
Fixes some issues around reading posts that were broken in an earlier build
https://streamable.com/12jvgh
=> Fixed some issues reading posts

Mlem/Views/Shared/Website Icon Complex.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListRowViews.swift
- https://github.com/mormaer/Mlem/issues/369
Removes the favorite button from VO so it doesn't take over the default action. 
Favorite is still available from the rotor.
Fixed some whitespace issues.
Fixed issues with links in posts
https://streamable.com/34bh5p
https://streamable.com/xd816v
=> Fixed issue with VO on community list view.

Mlem/Views/Tabs/Inbox/Feed/All Items Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Mentions Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Messages Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Replies Feed View.swift, Mlem/Views/Tabs/Inbox/Inbox View Logic.swift, Mlem/Views/Tabs/Inbox/Inbox View.swift
- This bug has no issues 😎 
- It's a tack-on to #338 
Inbox was using an `@State` when it shouldn't have. That's fixed, plus added a check to see if account has changed to trigger a reload. Some minor changes to the view structure in the feed views to properly show the loading indicator in that event.
=> Bugfix: inbox not reflecting change in accounts

Mlem/Views/Shared/Website Icon Complex.swift
- #322
I know we are planning to rework these views but this really annoyed me.
n/a
=> Link post images were leaking into their links (fixes #167)

Mlem.xcodeproj/project.pbxproj, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Block Community Button.swift
- #388
Adds a new option to the community taskbar menu to block/unblock.
This does not add a view to show all blocked communities so there isn't a good way to unblock in Mlem.  But it's a start.
=> Added block community button (fixes #388)

Mlem.xcodeproj/project.pbxproj, Mlem/Extensions/View - Handle Lemmy Links.swift, Mlem/Models/Navigation Contexts/Community Sidebar Link.swift, Mlem/Views/Shared/Loading View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar View.swift
- #407 
This PR reworks how we push the sidebar view.  It seems like the old code was still using an odd combo of navigation links and visibility bindings.
I reworked the view to be navigated to much like the rest of the views and updated the sidebar to allow for "lazy" loading of community details when none are provided.
Error loading details
n/a
=> Fixed sidebar moderator links + cleanup (fixes #407)

Mlem.xcodeproj/project.pbxproj, Mlem/Extensions/String.swift, Mlem/Views/Shared/Composer/PostComposerView.swift, Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/Links/User Profile Label.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/NSFW Tag.swift
Replaced old new post UI with a more accessible and extensible UI
Still to complete
- Error Handling.  (not sure what post failures will do right now)
Future Improvements not to be part of this PR
- Upload Images (I have the UI in place, but we need to get the API for uploading)
- Language Picker requires some new API work.
- Markdown formatting buttons (scope was too big for this PR)
=> New post UI

Mlem/Logic/Participating/Delete Post or Comment.swift, Mlem/Models/User-Interactable/Menu Function.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item Logic.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Ellipsis Menu.swift
- #309 
- #310
Definitely for the first time *cough* we can now delete comments and posts!
This PR also introduces the concept of "disabled" menu items and "destructive prompts" to ask the user to confirm their destructive action.
n/a
=> Added delete post and comment to menu (fixes #310, #309)

Mlem/Views/Shared/Composer/PostComposerView.swift
- *list issue(s) here*
Added URL validation
Fixed some minor spelling issues
Fixed some logic errors
=> URL validation and minor bugs.

Mlem/Extensions/Swipey Actions.swift, Mlem/Extensions/View - Handle Lemmy Links.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift
Dupe of #415 with merge conflicts resolved.
=> Swipe actions refactor

Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Profile/User View.swift
- n/a
Adds the following flags to `FeedPost` and `CommentItem`:
- `showInteractionBar` - This enables/disables the rendering of the interaction bar at the bottom
- `enableSwipeActions` - This enables/disables swipe actions
n/a
Useful for post composing views which are up and coming.
=> Added flags to disable swiping and interaction bar for posts and comments
